---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    run: redis
spec:
 containers:
 - name: redis
   image: kubernetes/redis:v1
   env:
   - name: MASTER
     value: "true"
   ports:
   - containerPort: 6379
   resources:
     limits:
       cpu: "0.1"
   volumeMounts:
   - mountPath: /redis-master-data
     name: data
   - mountPath: /redis-master
     name: config
 volumes:
   - name: data
     emptyDir: {}
   - name: config
     configMap:
       name: example-redis-config
       items:
       - key: redis-config
         path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-service
  name: redis-service
  namespace: default
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: redis
  type: ClusterIP        

